version: "3.5"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1 
      KAFKA_CREATE_TOPICS: data-topic:2:1 , data-mart-topic:1:1, auth-topic:1:1 
  db:
    image: postgres:11.4-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    volumes:
      - ./data-mart-service/db/schema.sql:/docker-entrypoint-initdb.d/mart.sql  
      - ./auth-service/db/token_schema.sql:/docker-entrypoint-initdb.d/auth-token.sql  
      - ./auth-service/db/user_schema.sql:/docker-entrypoint-initdb.d/auth-user.sql 
  data-collector-service:
    build:
      context: ./data-collector-service
      dockerfile: Dockerfile
    container_name: data-collector-service
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  processing-service:    
    build: 
      context: ./processing-service
      dockerfile: Dockerfile
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181    
  data-mart-service:    
    build: 
      context: ./data-mart-service
      dockerfile: Dockerfile
    container_name: data-mart-service
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "3002:3002" 
  auth-service:    
    build: 
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - zookeeper
      - kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "3001:3001"     